package com.rms.common.exception;

public enum ErrorCode {
    ERR_VALIDATION_FAILED,
    ERR_INVALID_STATE_TRANSITION,
    ERR_DUPLICATE_APPLICATION,
    ERR_JOB_NOT_ACCEPTING_APPLICATIONS,
    ERR_CV_IN_USE,
    ERR_CV_LIMIT_EXCEEDED,
    ERR_INVALID_FILE_TYPE,
    ERR_FILE_TOO_LARGE,
    ERR_OFFER_ALREADY_EXISTS,
    ERR_OFFER_INVALID_STAGE,
    ERR_INTERVIEW_PAST_DATE,
    ERR_MISSING_CREDENTIALS,
    ERR_TOKEN_EXPIRED,
    ERR_INVALID_TOKEN,
    ERR_INSUFFICIENT_PERMISSION,
    ERR_TENANT_MISMATCH,
    ERR_ACCOUNT_LOCKED,
    ERR_RESOURCE_NOT_FOUND,
    ERR_EMAIL_ALREADY_EXISTS,
    ERR_IDEMPOTENCY_CONFLICT,
    ERR_INTERNAL_SERVER_ERROR,
    ERR_SERVICE_UNAVAILABLE
}
